"use client";

import { Sparkles } from "lucide-react";
import type { MarketSummary } from "@aegis/contracts";
import { Card } from "@/components/ui/card";
import { formatRelativeTime } from "@/lib/format";

/**
 * The AI's read of the weather.
 *
 * It explains; it never decides (Founding Principle 9). It cannot create a
 * signal, cannot move a confidence score, cannot set leverage. It exists so a
 * trader can understand *why* the platform is behaving as it is — why Reversal
 * is standing down, why Thursday will be quiet.
 *
 * Labelled as AI wherever it appears, so nobody mistakes a summary for an
 * instruction.
 */
export function MarketSummaryCard({ summary }: { summary: MarketSummary }) {
  // The summary is deterministic today (the AI layer is a later milestone). Label
  // it honestly — an "AI" badge on a rule-generated line would be the exact kind of
  // misattribution this platform refuses.
  const isDeterministic = summary.model === "deterministic";

  return (
    <Card className="gap-3 p-5">
      <div className="flex items-center gap-2">
        <Sparkles className="size-4 text-primary" aria-hidden />
        <h2 className="text-sm font-semibold tracking-tight">
          What&apos;s happening
        </h2>
        <span className="rounded-md border px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
          {isDeterministic ? "AUTO" : "AI"}
        </span>
        <span className="ml-auto text-xs text-muted-foreground">
          {formatRelativeTime(summary.generatedAt)}
        </span>
      </div>

      <p className="text-sm leading-relaxed">{summary.summary}</p>

      <div className="space-y-1.5 border-t pt-3">
        <p className="label-caps text-muted-foreground">Watching</p>
        <ul className="space-y-1">
          {summary.watching.map((item) => (
            <li
              key={item}
              className="flex gap-2 text-sm leading-snug text-muted-foreground"
            >
              <span aria-hidden>·</span>
              {item}
            </li>
          ))}
        </ul>
      </div>

      <p className="text-xs text-muted-foreground">
        Generated by {summary.model}. This explains the market — it does not
        produce signals, and it cannot override a rule.
      </p>
    </Card>
  );
}
